EXP_NAME: ppo
TRACK: True
CAPTURE_VIDEO: True

EVAL_DURING_TRAIN: False
EVAL_EVERY: 1000

PIXEL_BASED: True
NATIVE_DOWNSCALING: True
SMOOTH_IMAGE: False

SAVE_MODEL: True
UPLOAD_MODEL: False
HF_ENTITY: ""

ENV_ID: pong
TRAIN_MODS: []
EVAL_MODS: []

TOTAL_TIMESTEPS: 10000000
LEARNING_RATE: 0.00025
NUM_ENVS: 8
NUM_STEPS: 128
ANNEAL_LR: True
GAMMA: 0.99
GAE_LAMBDA: 0.95
NUM_MINIBATCHES: 4
UPDATE_EPOCHS: 4
NORM_ADV: True
CLIP_COEF: 0.1
CLIP_VLOSS: False
ENT_COEF: 0.01
VF_COEF: 0.5
MAX_GRAD_NORM: 0.5
TARGET_KL: null
